import * as THREE from 'three'
import { mergeVertices } from 'three/examples/jsm/utils/BufferGeometryUtils.js'
import type { ParamValue } from '@/types/params'
import type { GeometryBrick } from './types'

/** Procedural mesh backend — the morph-compatible shape family
 *  (docs/03-ARCHITECTURE.md HC-4).
 *
 *  Every shape here is generated by DISPLACING one shared base topology: a welded
 *  icosphere. That is what makes any↔any vertex morphing work — `position` and
 *  `targetPosition` only interpolate cleanly when both have the same vertex count
 *  AND the same vertex correspondence. Authoring genuinely different meshes and
 *  lerping between them produces exploding, self-intersecting geometry.
 *
 *  The consequence, stated honestly: every shape in this family is topologically a
 *  sphere. The "torus" has no real hole — it is a sphere squeezed into a torus form,
 *  with the poles collapsing onto the inner equator. When a true genus-1 torus with
 *  correct UVs is needed, use the `primitive` backend instead and accept that it
 *  cannot vertex-morph. That trade is the entire reason both backends exist. */

/** Icosphere subdivision level.
 *
 *  Three.js PolyhedronGeometry splits each face into (detail+1)² triangles — NOT 4^detail
 *  as is commonly assumed. So faces = 20·(detail+1)², and by Euler's formula for a
 *  closed triangulated surface (V − E + F = 2 with 3F = 2E), the welded vertex count is
 *  F/2 + 2 = 10·(detail+1)² + 2.
 *
 *  detail = 7 → 1280 faces → 642 vertices: smooth enough for vertex deformation,
 *  cheap enough to clone dozens of times. */
const BASE_DETAIL = 7

/** Every geometry in this family reports exactly this vertex count.
 *  Enforced by assertMorphCompatible() — a silent mismatch here becomes exploding
 *  geometry mid-morph much later, so it fails loudly at build time instead. */
export const BASE_VERTEX_COUNT = 10 * Math.pow(BASE_DETAIL + 1, 2) + 2 // 642

/** All procedural bricks share this morph group. */
export const PROCEDURAL_MORPH_GROUP = `icosphere-${BASE_VERTEX_COUNT}`

/** The welded base icosphere, built once and reused as a read-only template. */
let baseGeometry: THREE.BufferGeometry | null = null

function getBaseGeometry(): THREE.BufferGeometry {
  if (!baseGeometry) {
    // IcosahedronGeometry is non-indexed (every triangle owns its three corners).
    // Welding is required: without it, displacement cracks the mesh open at every
    // shared edge, and the vertex count tracks triangle count rather than topology.
    const raw = new THREE.IcosahedronGeometry(1, BASE_DETAIL)

    // mergeVertices() welds on ALL attributes, so a UV seam or a differing normal
    // keeps two coincident vertices apart. That leaves a ring of duplicates along the
    // texture wrap — enough to break the shared-topology invariant. Position is the
    // only attribute that defines topology here, so drop the rest and rebuild normals
    // after welding. (Procedural shapes derive UVs from the base direction when they
    // need them; the base sphere's UVs are not meaningful post-displacement anyway.)
    raw.deleteAttribute('uv')
    raw.deleteAttribute('normal')

    baseGeometry = mergeVertices(raw)
    baseGeometry.computeVertexNormals()
    raw.dispose()

    const actual = baseGeometry.getAttribute('position').count
    if (actual !== BASE_VERTEX_COUNT) {
      throw new Error(
        `[proceduralMesh] base icosphere welded to ${actual} vertices, expected ` +
          `${BASE_VERTEX_COUNT}. BASE_VERTEX_COUNT and BASE_DETAIL have drifted apart.`,
      )
    }
  }
  return baseGeometry
}

/** Read the unit-sphere directions of the base topology. Stable ordering. */
function getBaseDirections(): Float32Array {
  return getBaseGeometry().getAttribute('position').array as Float32Array
}

// ─────────────────────────────────────────────────────────────────────────────
// Displacement functions: unit sphere direction → surface point
// ─────────────────────────────────────────────────────────────────────────────

type Displace = (
  nx: number,
  ny: number,
  nz: number,
  params: Record<string, ParamValue>,
  out: THREE.Vector3,
) => void

/** Project a direction onto a convex polyhedron defined by its face plane normals.
 *
 *  For a unit direction n, the surface point is n / max_i(n · N_i). This is the same
 *  operation for a cube (6 axis planes), an octahedron (8 diagonal planes), and an
 *  icosahedron (20 face planes) — one primitive covering three shapes. */
function projectToPolyhedron(
  nx: number,
  ny: number,
  nz: number,
  planes: number[][],
): number {
  let maxDot = 0
  for (const plane of planes) {
    const dot = Math.abs(nx * plane[0] + ny * plane[1] + nz * plane[2])
    if (dot > maxDot) maxDot = dot
  }
  return maxDot > 1e-6 ? 1 / maxDot : 1
}

const CUBE_PLANES = [
  [1, 0, 0],
  [0, 1, 0],
  [0, 0, 1],
]

const OCTAHEDRON_PLANES = (() => {
  const k = 1 / Math.sqrt(3)
  return [
    [k, k, k],
    [k, k, -k],
    [k, -k, k],
    [k, -k, -k],
  ]
})()

/** The 20 face normals of a regular icosahedron, deduplicated by sign. */
const ICOSAHEDRON_PLANES = (() => {
  const phi = (1 + Math.sqrt(5)) / 2
  const raw = [
    [0, 1, phi],
    [0, 1, -phi],
    [1, phi, 0],
    [1, -phi, 0],
    [phi, 0, 1],
    [-phi, 0, 1],
    [1, 1, 1],
    [1, 1, -1],
    [1, -1, 1],
    [1, -1, -1],
  ]
  return raw.map(([x, y, z]) => {
    const length = Math.hypot(x, y, z)
    return [x / length, y / length, z / length]
  })
})()

/** Blend between the pure sphere and a shape's projection.
 *  roundness 0 = full shape, 1 = sphere. Free, and musically useful as a morph target. */
function applyRoundness(scale: number, roundness: number): number {
  return scale + (1 - scale) * roundness
}

const num = (params: Record<string, ParamValue>, key: string, fallback: number): number => {
  const value = params[key]
  return typeof value === 'number' ? value : fallback
}

const displaceSphere: Displace = (nx, ny, nz, params, out) => {
  const r = num(params, 'radius', 1)
  out.set(nx * r, ny * r, nz * r)
}

function polyhedronDisplacer(planes: number[][]): Displace {
  return (nx, ny, nz, params, out) => {
    const r = num(params, 'radius', 1)
    const roundness = num(params, 'roundness', 0)
    const scale = applyRoundness(projectToPolyhedron(nx, ny, nz, planes), roundness) * r
    out.set(nx * scale, ny * scale, nz * scale)
  }
}

/** Sphere → torus form.
 *
 *  Azimuth drives the major angle; polar angle drives the minor angle. Because the
 *  sphere's two poles both map to minor angle 0, they collapse onto the inner equator
 *  circle — the shape reads as a torus but is still genus 0. See the file header. */
const displaceTorus: Displace = (nx, ny, nz, params, out) => {
  const major = num(params, 'radius', 1)
  const minor = num(params, 'tube', 0.35)

  const azimuth = Math.atan2(nz, nx)
  const polar = Math.acos(Math.min(1, Math.max(-1, ny)))
  const minorAngle = polar * 2 // [0, π] → [0, 2π]

  const ringRadius = major + minor * Math.cos(minorAngle)
  out.set(Math.cos(azimuth) * ringRadius, minor * Math.sin(minorAngle), Math.sin(azimuth) * ringRadius)
}

/** Sphere → capped cylinder, by clamping against the side wall and the two caps. */
const displaceCylinder: Displace = (nx, ny, nz, params, out) => {
  const r = num(params, 'radius', 1)
  const halfHeight = num(params, 'height', 2) / 2
  const roundness = num(params, 'roundness', 0)

  const radial = Math.hypot(nx, nz)
  const sideScale = radial > 1e-6 ? 1 / radial : Number.POSITIVE_INFINITY
  const capScale = Math.abs(ny) > 1e-6 ? halfHeight / (r * Math.abs(ny)) : Number.POSITIVE_INFINITY
  const scale = applyRoundness(Math.min(sideScale, capScale), roundness) * r

  out.set(nx * scale, ny * scale, nz * scale)
}

/** Sphere → cone: radius tapers linearly from base to apex. */
const displaceCone: Displace = (nx, ny, nz, params, out) => {
  const r = num(params, 'radius', 1)
  const halfHeight = num(params, 'height', 2) / 2

  // Map the vertical direction to a normalised height, then taper.
  const t = (ny + 1) / 2 // 0 at bottom, 1 at apex
  const y = -halfHeight + t * halfHeight * 2
  const taper = 1 - t
  const radial = Math.hypot(nx, nz)
  const scale = radial > 1e-6 ? (r * taper) / radial : 0

  out.set(nx * scale, y, nz * scale)
}

// ─────────────────────────────────────────────────────────────────────────────
// Geometry construction
// ─────────────────────────────────────────────────────────────────────────────

/** Build a geometry by displacing the shared base topology.
 *  The returned geometry always has BASE_VERTEX_COUNT vertices and the base index. */
function buildDisplaced(
  displace: Displace,
  params: Record<string, ParamValue>,
): THREE.BufferGeometry {
  const base = getBaseGeometry()
  const directions = getBaseDirections()
  const vertexCount = directions.length / 3

  const positions = new Float32Array(directions.length)
  const point = new THREE.Vector3()

  for (let i = 0; i < vertexCount; i++) {
    const o = i * 3
    displace(directions[o], directions[o + 1], directions[o + 2], params, point)
    positions[o] = point.x
    positions[o + 1] = point.y
    positions[o + 2] = point.z
  }

  const geometry = new THREE.BufferGeometry()
  geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3))
  const index = base.getIndex()
  if (index) geometry.setIndex(index.clone())
  // Keep the undisplaced sphere directions available: deformers that push "along the
  // original normal" and the morph engine both need the shared reference frame.
  geometry.setAttribute('baseDirection', new THREE.BufferAttribute(directions.slice(), 3))
  geometry.computeVertexNormals()
  geometry.computeBoundingSphere()

  return geometry
}

/** Fail loudly if a geometry has drifted off the shared topology.
 *  A silent mismatch here becomes corrupted morphing much later, far from the cause. */
export function assertMorphCompatible(geometry: THREE.BufferGeometry, brickId: string): void {
  const count = geometry.getAttribute('position').count
  if (count !== BASE_VERTEX_COUNT) {
    throw new Error(
      `[proceduralMesh] "${brickId}" produced ${count} vertices, expected ${BASE_VERTEX_COUNT}. ` +
        `Every procedural brick must displace the shared base topology, not build its own mesh.`,
    )
  }
}

const RADIUS = {
  key: 'radius',
  label: 'Radius',
  type: 'float' as const,
  min: 0.01,
  max: 50,
  step: 0.05,
  defaultValue: 5,
  unit: 'm' as const,
  group: 'Geometry',
  exposed: true,
}

const ROUNDNESS = {
  key: 'roundness',
  label: 'Roundness',
  type: 'float' as const,
  min: 0,
  max: 1,
  step: 0.01,
  defaultValue: 0,
  group: 'Geometry',
  exposed: true,
}

const HEIGHT = {
  key: 'height',
  label: 'Height',
  type: 'float' as const,
  min: 0.01,
  max: 100,
  step: 0.05,
  defaultValue: 10,
  unit: 'm' as const,
  group: 'Geometry',
  exposed: true,
}

function proceduralBrick(
  id: string,
  label: string,
  displace: Displace,
  extraDescriptors: GeometryBrick['descriptors'],
): GeometryBrick {
  return {
    id,
    label,
    backend: 'mesh',
    meshKind: 'procedural',
    morphGroup: PROCEDURAL_MORPH_GROUP,
    descriptors: [RADIUS, ...extraDescriptors],
    build: (params) => {
      const geometry = buildDisplaced(displace, params)
      assertMorphCompatible(geometry, id)
      return geometry
    },
  }
}

export const PROCEDURAL_BRICKS: GeometryBrick[] = [
  proceduralBrick('proc-sphere', 'Sphere', displaceSphere, []),
  proceduralBrick('proc-cube', 'Cube', polyhedronDisplacer(CUBE_PLANES), [ROUNDNESS]),
  proceduralBrick('proc-octahedron', 'Octahedron', polyhedronDisplacer(OCTAHEDRON_PLANES), [ROUNDNESS]),
  proceduralBrick('proc-icosahedron', 'Icosahedron', polyhedronDisplacer(ICOSAHEDRON_PLANES), [ROUNDNESS]),
  proceduralBrick('proc-torus', 'Torus', displaceTorus, [
    {
      key: 'tube',
      label: 'Tube',
      type: 'float',
      min: 0.01,
      max: 20,
      step: 0.05,
      defaultValue: 1.6,
      unit: 'm',
      group: 'Geometry',
      exposed: true,
    },
  ]),
  proceduralBrick('proc-cylinder', 'Cylinder', displaceCylinder, [HEIGHT, ROUNDNESS]),
  proceduralBrick('proc-cone', 'Cone', displaceCone, [HEIGHT]),
]
